spring.application.name=apiCompraventaDeVehiculo


#Ingresar las credenciales para la conexion con my sql
spring.datasource.url=jdbc:mysql://localhost:3306/compraventavehiculos

#Datos del usuario
spring.datasource.username=root

#Contraseña
spring.datasource.password=

#Driver de my sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa con hibernate mantener la base de datos actualizada
spring.jpa.hibernate.ddl-auto=update

#Mostrar las instrucciones de sql por consola
spring.jpa.show=true
